-- CreateTable
CREATE TABLE "PurchasePrice" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "tankId" INTEGER NOT NULL,
    "price" DECIMAL NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PurchasePrice_tankId_fkey" FOREIGN KEY ("tankId") REFERENCES "Tank" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
